logging:
  pattern:
    console: "[Organization Development] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  
server:
  port: 8885
  
spring:
  main:
    banner-mode: OFF
  kafka:
    listener:
      missing-topics-fatal: false
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer        
    consumer:
      group-id: organization-development-cg
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    bootstrap-servers: ${docker.host}:9092
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: ${docker.host}
      discovery:
        prefer-ip-address: true
        ip-address: ${service.ip-address}
        health-check-path: /ping
  datasource:
    url: "jdbc:mysql://${docker.host}:3306/organization_development"
    username: user
    password: userpassword
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

feign:
  hystrix:
    enabled: false
    
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 30s
        record-exceptions:
          - feign.RetryableException
  retry:
    configs:
      default:
        max-retry-attempts: 30
        wait-duration: 5s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true